### ISSUE TITLE
Program shows wrong Synch spread

### ISSUE THREAD

**Issue by Real96** [Quandra/PokemonSunMoonRNGTool#20]
Sometimes the program shows the wrong synch of the spreads. It says that a spread is Synchronizable but it isn't instead.

**Comment by Quandra** [comment]
According to this post (http://www.smogon.com/forums/threads/sfmt-rng-in-sun-moon.3591281/page-2#post-7211058), blinking process may occurs 2 times after  synchronize. So sometimes it will be different from the tool.

**Comment by Real96** [comment]
Uh, ok. Just close this issue then and thanks for your great work!
