### ISSUE TITLE
Shiny charm for Type:Null

### ISSUE THREAD

**Issue by Real96** [Quandra/PokemonSunMoonRNGTool#28]
Can you add it? I think it can be really useful to search shiny spreads with High IVs

**Comment by wwwwwwzx** [comment]
Unfortunately, it seems that shiny charm doesn't work for Type:Null.

**Comment by Real96** [comment]
Uh. Is it sure this thing?

**Comment by wwwwwwzx** [comment]
Pretty sure. I have the shiny charm and I can see my Type:Null use the RN right after the encryption constant as its PID, which means the game only roll 1 RN for PID instead of 3.

**Comment by Real96** [comment]
Undeestood. Close this issue then t.t
